### PR TITLE
Recipe & tag model

### PR DESCRIPTION
**Pull request by junrong09**

### CODE REVIEW

**Comment by junrong09** [comment]
Please take note of the Instruction.java class as it contains ingredients used by each instruction.

**Comment by junrong09** [comment]
Please take note of the recipe model in case you guys need to make use of the information. Additional information (address, phone, email) will be removed after logic and storage is ready to be extended.

**Review by BennTay — DISMISSED** [review]
Minor issues for Recipe.java:
Maybe can remove the Phone and Email attributes along with their getters/setters from Recipe.java.
Dead code at lines 43, 44 and 45 can be deleted.

Otherwise good code!

**Review by AlecNgZW — COMMENTED** [review]
Adding of recipe cooking portion extension as well as tag list, does not seem to have issues.

**Review by barkhyehyeon — COMMENTED** [review]
Good implementation for Recipe & Tag model! Approve PR.

**Review by barkhyehyeon — APPROVED** [review]
Good implementation for Recipe & Tag model! Approve PR.

**Pull request merged**
