### PR TITLE
Model revamp v2

### PR DESCRIPTION
**Pull request by junrong09**

### CODE REVIEW

**Review by AlecNgZW — COMMENTED** [review]
preliminary review of branch:

- Clean level 2 package refactoring from address to souschef

- Change of details in the .adoc files relevant to souschef

- Recreation of Model class to act as a superclass with generic that holds the entities for each of the function as a wrapper for the function calls. (one function handles everything and depends on the passing of entity generic)

- Replacement of old function calls to the new generic function calls

- Creation of generic type classes to wrapper for the relevant children of that type of file.

Overall, the branch looks clean and is green-lighted on my end. To wait for the reviews of the others. 
Good job Jun Rong

**Review by AlecNgZW — COMMENTED** [review]
replacement of original implementation with new ModelManager call.
Looks fine

**Review by AlecNgZW — APPROVED** [review]
Program based refactoring from address to souschef

**Review by barkhyehyeon — COMMENTED** [review]
Approve PR

**Pull request merged**
